### PR TITLE
Missed mocha this context

### PR DESCRIPTION
**Pull request by lbeschastny**

### CODE REVIEW

**Comment by lbeschastny** [comment]
My test wasn't accurate, feature still not working.

**Comment by lbeschastny** [comment]
You still can't access `Context` from within an arrow function, but it's an arrow function feature.
Probably, it should be reflected in readme.

**Comment by jlipps** [comment]
@Jonahss / @moiz, maybe this issue explains the problems you were having with `this` the other day

**Comment by lbeschastny** [comment]
[Here is a link, explaining arrow functions behavior.](https://babeljs.io/docs/learn-es2015/#arrows)

> Unlike functions, arrows share the same lexical `this` as their surrounding code.

Which means that arrow functions share `this` context they were created in, rather than the one they were called in.

**Comment by vaukalak** [comment]
👍 for that feature. shared behaviors is highly important feature of mocha https://github.com/mochajs/mocha/wiki/Shared-Behaviours. The provided fix works perfectly, what the reason to not merge it in?

**Comment by jlipps** [comment]
ok merged it, but this project is deprecated anyway as mocha supports all its features natively now

**Comment by lbeschastny** [comment]
@jlipps you do realize that merging this PR without releasing new version to `npm` is quite pointless, do you?

And you didn't push deprecation note to `npm` yet, so not all `mochawait` users are seeing it.

**Comment by jlipps** [comment]
@lbeschastny yes i am in the process of releasing a new version

**Pull request merged**
